name: Create Release Tarball

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
          submodules: 'recursive'

      - name: Package Project
        run: tar -czf /tmp/huml-${{ github.ref_name }}.tar.gz --exclude='.git' .

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          draft: true
          files: /tmp/huml-${{ github.ref_name }}.tar.gz
